### ISSUE TITLE
Create a Wireframe of the App

### ISSUE THREAD

**Issue by estermer** [ga-wdi-pvd/ga-wire#2]
wireframe the general look of the app

**Comment by tvlangley** [comment]
We'll be modeling the structure of the app by a pre-established website TBD

**Comment by estermer** [comment]
Here are some links for some forums for inspiration

http://www.theverge.com/forums/gaming

https://forum.blockstack.org/

https://generalassemb.ly/

**Comment by tvlangley** [comment]
![GA Wire Wireframe](https://cloud.githubusercontent.com/assets/13801825/22652991/4c787414-ec56-11e6-858b-f0d12b5e0da6.png)

**Comment by estermer** [comment]
This is great!!!!!

**Comment by estermer** [comment]
Make sure you post this in the readme

**Comment by estermer** [comment]
Alright I added the wireframe to the readme.
