### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by estermer** [ga-wdi-pvd/ga-wire#3]
Discuss what Models we want and their relationships

**Comment by estermer** [comment]
We are obviously going to have:

`User`
`Post`
`Comments`

but what else should we have or should we say these 3 for now as a bronze and then come up with more as a silver or gold reach goals?

Silver:
`Categories`
`Cities`

Gold:

`Likes` or `Hearts`
`Reply`
`Instructors`
`Administrators`?

**Comment by JosephinaTavera** [comment]
Sound like a great starting point.

**Comment by estermer** [comment]
OK so far I decided that replies are useless and so should just have comments.

Also I decided on cities can be a category

categories are not hard so they can be done as a quick silver goal and same thing for likes.

I think the Gold would have to be like an up vote and a down vote.

Bronze:
`User`
`Post`
`Comment`

Silver:
`Category`
`Likes`

Gold:
`Votes`

**Comment by estermer** [comment]
So I add the ERD to the README

Let me know if it needs work

**Comment by estermer** [comment]
I am just going to accept what I have for now and if we need to change it, then we will
