### ISSUE TITLE
Decide on stacks

### ISSUE THREAD

**Issue by estermer** [ga-wdi-pvd/ga-wire#4]
What stacks should we use? What gems or ways for user auth should we use? 3rd party api's?

**Comment by JosephinaTavera** [comment]
I am in agreement with Toni

**Comment by estermer** [comment]
i am wondering... is there a way to use SQL databases using node? or is node restricted to merely Mongo?

**Comment by estermer** [comment]
http://mherman.org/blog/2015/02/12/postgresql-and-nodejs/#.WJT1SbYrLfY

^^^^ here is a walkthrough to do it? unless we wanna just use rails because it is fast?

**Comment by tvlangley** [comment]
We can do the same type of relationships using mongodb (one-to-one, one-to-many, many-to-many) but using sql with node would definitely be different for us.

**Comment by JosephinaTavera** [comment]
Hmm, that would be a good challenge

**Comment by tvlangley** [comment]
Rails would be the best bet since we have Danny who has years of real world experience in it.
